<div class="content"> 
	<?php if (!count($this->items)): ?>
		<b>No item(s) found!</b>
	<?php else: ?>
		<?php foreach ($this->items as $item): ?>
			<div class="item">
				<dl>
					<dt>ID: <dd><?php echo $item['id'] ?>
					<dt>Title: <dd><?php echo $item['title'] ?>
					<dt>Synopsis: <dd><?php echo $item['synopsis'] ?>
					<dt><a href="/v1/item/<?php echo $item['id'] ?>">Details: </a>
				</dl>
			</div>
		<?php endforeach; ?>
		<?php endif ?>
</div>