services:
    _defaults:
       autowire: true
       autoconfigure: true

    Loopia\App\Controllers\:
        resource: '../../src/Loopia/App/Controllers/'
        public: true
        
    application:
        class: Loopia\App\Core\FilmApiHttpApplication
        public: true

    Loopia\App\Api\FilmApiDataLoader:
        # arguments:
        #     $filmApiClient: '@Loopia\App\Api\Client'
        #     $redis: '@Loopia\App\Api\Client'

    Loopia\App\Core\DispatcherFactory:
        arguments:
            $routes: '%routes%'

    FastRoute\Dispatcher:
        factory: ['@Loopia\App\Core\DispatcherFactory', 'createDispatcher']